# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2864c7ca4c10685192b140f0a25358fb57873c3ba677c9ab8f3ea29d13c161d8115d5cca2e44344b8e2d4548a248e79ba3ccb03769780f863faee7899568ccf9

test:
  secret_key_base: 7d143ab217173a8753a2a77de00506f0f7728b0c1fb3be39e5dbc6723f2bec4ae7ae7806936accb3ba2485e6b436b2e1555267796f35adb2a85dd836c3f714c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
